module.exports = [
    "tacos parados",
    "tacos estilo norteño",
    "tacos al pastor",
    "quesadillas en harina y maiz",
    "quesadillas chilangas",
    "tacos de suadero",
    "los infaltables de caballo",
    "tacos elegantes",
    "tacos para pobres",
    "tacos que ni saidth y cesar se comen a las 12 de la noche en piedras",
    "tacos de mier..coles",
    "tacos de ver...duras",
    "tacos estilo monterrey",
    "tacos huastecos",
    "tacos de chino",
    "tacos de pescado",
    "tacos en honor al futbol",
    "tacos para los fanaticos de los tigres",
    "tacos para los perderores",
    "tacos mandilones para los que su señora les pega",
    "tacos de quien sabe que, quiero llenar la array",
    "tacos de es más rápido inventarmelos que buscarlos en internet",
    "tacos de ickkck",
    "burritos de alambre y bofo",
    "tacos para retrasados",
    "tacos para gente poco inteligente",
    "tacos 5 x 10",
    "los famosos tacos de canasta",
    "tacos parados",
    "tacos whitexicans",
    "tacos millenials, se quejan de todo",
    "tacos con tortilla de maiz",
    "tacos veganos",
    "tacos quemados"

    
]