module.exports = [
'Vamos al taco',
'La Taqueríta',
'Señor Taco',
'La Barra Del Taco',
'La Taqueña',
'La Comalita Taqueria',
'Tacos De La Madre',
'El Pastor Del Taco',
'Taco Town',
'La Condesa del Taco',
'El Tizón Picante',
'Más Que Tacos',
'El Carbón Rojo',
'La Chilanguita Picante',
'Que Chulada Taqueria',
'El Rancho Del Taco',
'El Taco Imperial',
'La Paisana Del Taco',
'Carnitas Doradas',
'El Jalapeño Verde',
'Los Tacos De La Nona',
'El Punto Del Mexicano',
'Carnitas Norteñas',
'Taquería Antígona',
'La Aldea Del Taco',
'La Sonora Del Taco',
'La Esquina De México',
'Taquería La Arábiga',
'La Canasta Del Taco',
'El Taconazo',
'La Fontana Taquería',
'La Alameda Taquería',
'Los Tacos De Hidalgo',
'El Fogonazo Del Taco',
'La Elite Del Taco'
]